notifications:
  email: false
language: node_js
node_js:
- 6.9.1
- node
sudo: false
dist: trusty
before_script:
- npm run lint
- npm run build
before_install:
- npm install buffer-shims
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
before_deploy:
- node ./write-version.js
- npm run build
after_success: npm run coveralls
deploy:
- provider: script
  skip_cleanup: true
  script: cd $TRAVIS_BUILD_DIR; ./build-and-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: mN3WSX1M7gLg140H0fwg3LjSAS8jtcAm8gLUcPc65BBO/BFnD1g6JNSFo4SMXTJpX2z0Bx5tNd+rKfqkQXjhfRXmS0RZwNyUgx/EtcQ38CH8sZa0+HKinwZu5O88ktHJ8avOJ/ebSKRAUgyXAmU6wNoTHT5f8OCkDi3dtWIYGFKAQfq9EjtfWV8h4cY3OOYqAdbpJNhUzkHgQ/WiNuFxghAcku6t3QztqsSTP0Q9xYIFx03gZgSztnDoQZfgxVpwj5gIsK9heu6EcJh5S9dYSsyoeqoT7vEZujLxF1g3t1G5bREcCCsLYxYdmsTrgDm3cexWxHxERH2i40YsT7DVuKL4yvWT55nkNJlkqMwWCGJSrdoxqb6c750yW4t/lvU3HVjxS2MI7oS1sPlSB3KVyvd5A0+G/yykJRZocJo0iyZ+WvbNuz6/9Q9wGJH7IgXJjarZgwPAblUZ991MUVO8O/zSMCpNg3VK49FHLwYoAIJGW4IPL25XDQuI+3ObWVpBzUg43J46Cij3ZEDXmVCvRd8lpiBoU7NGZkGE18Bxrl5yvaQJssM8KvBuBNDi005FT+5esPd+yJQSXdf5pXyxMlOhO0eYCkf9XX6DDh/U6DgTT73XK7TU7T5SH9LS2PDS6qL8Exry0UpY3sTjkcxDO1cDO3+ivkO2v/TIy15Avp4=
  - secure: DzyMXU4E26NlSVVwe2oC2NMOi9Pe0rIDnQKAwPQFX3xOXLqJNpj++RYpc2y1xeXQP1DgDSYT/zWx/DN/hqp8Wcg19ky/7knVaheyJG1aw35d0j4ls0mikt1M9ipFab/vx/uCUvie/M14FA/2YI654ZcZa332CGXfosqUKFL+EFoCupRPvSb0PhZ80vPx1liTaj3NhrMTcSin0C+vlNCI+oj2nWdrRo5rduLEu3NbBmX7O5YyslR5c+IYyFREioH3/HzT1DZL28I3ad8nWidqYIG09tHVNDRI4aoO6ykZrygZ7ciAAsCZOEpQJZbBKZTCpo6Voewm4r0MpCOODcK717hW025YaBJcOJ1Qm7rluCLbgHmzHC8hiZSSnFodpaDW4JlfpSS0PWkCzJ0cXN2DzGfmZlD/s9gzr/t0/XL1WWHKf/wDUFtFXIwFfyLlcdMKAuBr1cpC6l3nVmyaaBY2jazpOQpBoGcilvrJpweuncRs3ZufCGL/79w3Tx3v/3RjwebKMwCJNx8Kz1kuSOn6fSizt4+XdsKJUmkNNbmWn1162jk+FolHEGMjPqV6XEkcJBOiZreKEtxTQB0pARBZKz8zsXs/4LyiapitiwLxs/kj/VW3KPYeHClDC4zrDp4bqw7VLuMQEdqbDINL04ec8khsNpkFDCdZmQy/y9/hKJM=
  - secure: nyzQ3XaA4KxEpw2jDqUaAIEVF3k5VLBqVnX9n16zOVhKGQ7I7HfbVVVQlFXqf1aHWKX5qPwYgsFNNSU3VfxUpll6R4NYIPA5YRfOFgDGLiInUmjNMmqOuH58Ros8BAZ4rVh7XTSMhyYDq6KxowUXdIq6hxMVXLisQGfkfVFC+x/OBWVztfDgcJM7mcy+i6/mOzyGNKnldJ6wuSDZduP21GGQwqRZLLwPK2MBbD5SlbvtQJG/SqmtdKn/KBZV4ZMgaYkdzTUTd/I2OQaT4r2d3JaG8F/JsP+MlCnOXEOUgh6Trna7rvxJmHtlDiGogmjP6ewnOZgvZ3F6nZ8aiwB9FhnvQ+xdt5cKJRngfOXEA8UIPeXriHxbGZZpPBXpO13XQdLRgCnrur2ZBIxeYyKdcXA6Eminl/U+REaBZpUFEt6XL8CMWbDTiDpVv7dfA+SVfGEnmNhmW4mvBNVY5WaF6zO7JkBJCmk0LCISzhUmxxDbp14vtmOnHRxrKhbU0GcOhPIv7RVqf3k9O95nhuBNpc2mhMuULKoF1d1UHji6mJX8VPd7nuMbjxj9BXSY/+fmVaGtSLxHFMarpf1FSqgi7osVexnnz2e2fJLN0u/81OVJbw1OjdpsQdW9lx5PS3nsNv2EMApt9M5MaDY9bT6p8e3brUUrzhE22hq5ZBfXjP8=
